#meunumero = int(input('digite seu numero'))
#resultado1 = meunumero * 1
#numero1 = 1
#resultado2 = meunumero * 2
#numero2 = 2
#resultado3 = meunumero * 3
#numero3 = 3
#resultado4 = meunumero * 4
#numero4 = 4
#r#esultado5 = meunumero * 5
#numero5 = 5
#resultado6 = meunumero * 6
#numero6 = 6
#resultado7 = meunumero * 7
#numero7 = 7
#resultado8 = meunumero * 8
#numero8 = 8
#resultado9 = meunumero * 9
#numero9 = 9
#resultado10 = meunumero * 10
#numero10 = 10
#print('á tabuada é {} * {} = {}'.format(meunumero, numero1,  resultado1))
#print('á tabuada é {} * {} = {}'.format(meunumero, numero2,  resultado2))
#print('á tabuada é {} * {} = {}'.format(meunumero, numero3,  resultado3))
#print('á tabuada é {} * {} = {}'.format(meunumero, numero4,  resultado4))
#print('á tab#uada é {} * {} = {}'.format(meunumero, numero5,  resultado5))
#print('á tabuada é {} * {} = {}'.format(meunumero, numero6,  resultado6))
#print('á tabuada é {} * {} = {}'.format(meunumero, numero7,  resultado7))
#print('á tabuada é {} * {} = {}'.format(meunumero, numero8,  resultado8))
#print('á tabuada é {} * {} = {}'.format(meunumero, numero9,  resultado9))
#print('á tabuada é {} * {} = {}'.format(meunumero, numero10,  resultado10))

